#ENC[AES256_GCM,data:2rslfS8AOBe2lCuo4pcqqr1wTyvaFnc/7RE=,iv:neknizXGsaNRR+6AprAUPVXuDRjG5VaMjGtzRdYOXWA=,tag:+fuOmMKXtWKKLk+gr+pXVA==,type:comment]
#ENC[AES256_GCM,data:NsACoGZmGW/pflO7gwwwvzNk2ozJCjLF/HJ0A/vyBC5UktF/Iknfgz+AC1pkQyQ1Gdk=,iv:F+jQI3hhbb8vQaQqq40vctuBlz9ciig3v5EtWED0uzg=,tag:7lrpLzNRlYwXGAkcfmhs/w==,type:comment]
#ENC[AES256_GCM,data:gcvTxfdlg+m0IC8aPvlZldNTBj8HB6hcTMhEXQSyzsJriBrfI7gs8xhNf/gBU9hYXRY=,iv:9ybo4O2oc6v9etrZ/RJJo+clxIq0Eb7/EhXcYn1Mmlk=,tag:jXwIuU3RL+Ca9MjRZn4bfg==,type:comment]
#ENC[AES256_GCM,data:BTZKft4pZ/v3WXxzXebZDmIkKcrd8gT+jFFxjZaAZ/DwgA20pU/h6Mnz88YE0jY=,iv:xt1LXLJbbzHWJybnhy+QG9aIY/Q+5nByIJ8Vv20riNE=,tag:GojuZG7VRW2eYlX3nwLgvg==,type:comment]
#ENC[AES256_GCM,data:qrVr2shhIJKrITnO1di79U/K8f7QXXLlpMZT5okByAn2IHVB7aTTRkFt/2Jktk/QsP5enI2NoZBl/dE2ldEf5EcAWi1CRvR1qA==,iv:Le81ECa7ktchogAXgbzRyZyVw+xKhMUpeBkB6UT5e/I=,tag:rR2rXNLTxuNNZgPNq2cKeQ==,type:comment]
apiVersion: ENC[AES256_GCM,data:bt8=,iv:6LTRB1adxeBlVd2c08Y6REfA8JGaP9nfifz/tpTEdZk=,tag:Hmwb0FULkB4cV1OEStvDwA==,type:str]
kind: ENC[AES256_GCM,data:WUy1zLpE,iv:RlFTFE2cGsk9zUjKqRZgjEnuirFK/S2FF58bIUhaPUs=,tag:g0kvbYYliF9tBiGXEp7gvQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:BNxkNXnfGIMLJDi1GvdpbauWbDo=,iv:oWNZw9zUe/lJsxg8uISa1aOrRzXgDAXHM09fKTy7Gto=,tag:zx5CdEbjrlbXT9VPmWoK6g==,type:str]
    namespace: ENC[AES256_GCM,data:3+kQXvkuGR6bfQ==,iv:msbZdvLb4Q0IuUAxpaDtIH0QPI0dZObWlg7sk6lbj3Q=,tag:KxwjO4demj6FCoeldiz0WA==,type:str]
    labels:
        app: ENC[AES256_GCM,data:NgUvOjgb4w==,iv:xe42P8HN6nBlPbIq4LtRUz6CBafcMFMwaK6UPs4TV0E=,tag:TI2n9MovdM8VOHuXPdB8AA==,type:str]
type: ENC[AES256_GCM,data:Y+pbKQSM,iv:+sICu7+WhCRPtrNHaVSSleg9bV3i1U92DkyGbLZ2oKc=,tag:tj+NPO9WnmUGVe0URLdXhg==,type:str]
stringData:
    #ENC[AES256_GCM,data:SDNxmmcBTr68/HoTuIG1BYxUV/nGB/VQxwi87kX3i5ll/Mo0rtrMxissmJnUc+bsTQYyMkuGfaOX9Pt9jk/nIMerFg==,iv:QM+QwOClTPXtxPmV+SsaaeCDLVt8a2n9lbD4V6pJKto=,tag:+TwTuMwM/983QYvpg0waag==,type:comment]
    GF_SECURITY_ADMIN_USER: ENC[AES256_GCM,data:hE9+h7U=,iv:gvnwHgS/PMb/w7r4zM2vNgua8ATAXU5jmhs/nz4Likc=,tag:59YItwc22TVmpakCqiUUlA==,type:str]
    GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:hfKQPDo=,iv:0LY7umAyDpyg1v+TuZi3qR9b4s1VKOAKh6Dm5DaBHKs=,tag:3PWd1TIlYT6HPobwdHxfuw==,type:str]
sops:
    age:
        - recipient: age14c4u5y4uf869su746ghhear0ys4p6fuj6r0pvzrujj03dwh3xals40k30e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwckV4UDN0VXhQVVp2dVNQ
            Mk02ZEFpdmd5QVUzUUJqa3hFSG5taWkwSEZzCkh5MmxVQkIrTVErdUZ6cUtrbHpq
            VjFTajFkMUtleFYyYWdYN3ZCSWNvOW8KLS0tIEtMN2NGbFZidkFxTGQ0UklQeUpi
            VFF1N3FxS1diamY2NGV1ZlBqbnlUWDQKVrrNmepa7IxHSZKjw4wsEns/0pjDTfye
            ebi84YZSBI3y/tmu+sqJl+wAPPklNPl5YJ4RtZCvJElz2dgFuXVzsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-10T15:59:24Z"
    mac: ENC[AES256_GCM,data:iQ38VZNmJeViEc13NpoBVJlgoRceX7gyVRJ51IXNjnwwowzLEmONm9IwqmK3E/KJsJpqyRdO7q12ij9UGMC0sdeoY/BMYfRNyD1NhX6rojh7D/DjAb+d9gONMCQZoR4/bxz5ND1arohQUceQtOvYoMHcP8C2Ub0ibhS9LgmwTq4=,iv:hG191SoGMCP6HktIsufI4P+xRZW6+2Br1rZmuN3vFK8=,tag:ngUhUrIy+PHv/ihm6dUchQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
